### ISSUE TITLE
Add it as an interactive option to `gev`

### ISSUE THREAD

**Issue by ftzi** [SrBrahma/eslint-config-gev#6]
I keep having to come back to this repo to find the commands because i just forget.

I could just have it and prettier under `gev`, that when executed it could use inquirer etc to choose what to do.

This package could also have an inquirer for the flavors.

**Comment by SrBrahma** [comment]
For the npx to this repo, check if eslint exists before and a prompt to overwrite it.

**Comment by SrBrahma** [comment]
This package already has a npx. I don't like anymore passing this utility to gev.
